export default {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    VISIBILITY_FILTER: 'VISIBILITY_FILTER',
    CLEAR_VALUE: 'CLEAR_VALUE',
    CHANGE_VALUE: 'CHANGE_VALUE'
};